// POST ACTION TYPES
export const GET_ALL_POSTS_REQUEST = 'GET_ALL_POSTS_REQUEST';
export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCCESS';
export const GET_ALL_POSTS_FAIL = 'GET_ALL_POSTS_FAIL';

export const GET_POST_BY_ID_REQUEST = 'GET_POST_BY_ID_REQUEST';
export const GET_POST_BY_ID_SUCCESS = 'GET_POST_BY_ID_SUCCESS';
export const GET_POST_BY_ID_FAIL = 'GET_POST_BY_ID_FAIL';

export const DELETE_POST_BY_ID_REQUEST = 'DELETE_POST_BY_ID_REQUEST';
export const DELETE_POST_BY_ID_SUCCESS = 'DELETE_POST_BY_ID_SUCCESS';
export const DELETE_POST_BY_ID_FAIL = 'DELETE_POST_BY_ID_FAIL';

export const ADD_POST_REQEUST = 'ADD_POST_REQEUST';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_FAIL = 'ADD_POST_FAIL';